// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "ArticyRuntime/Public/ArticyGlobalVariables.h"
#include "PluginshowcaseGlobalVariables.generated.h"

UCLASS(BlueprintType)
class UPluginshowcaseStringGlobalsVariables : public UArticyBaseVariableSet
{
	GENERATED_BODY()
	
public:
	/** This is a test variable */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Instanced, Category="StringGlobals")
	UArticyString* TestString = nullptr;
	/** This is a test int */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Instanced, Category="StringGlobals")
	UArticyInt* TestInt = nullptr;
	/** bool */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Instanced, Category="StringGlobals")
	UArticyBool* TestBool = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Instanced, Category="StringGlobals")
	UArticyBool* TestTest = nullptr;
	/** test */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Instanced, Category="StringGlobals")
	UArticyBool* Var2 = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Instanced, Category="StringGlobals")
	UArticyBool* C1_S1_Homarang_Fishing = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Instanced, Category="StringGlobals")
	UArticyBool* Var5 = nullptr;
	
	 UPluginshowcaseStringGlobalsVariables() 
	{
		TestString = CreateDefaultSubobject<UArticyString>("TestString");
		TestInt = CreateDefaultSubobject<UArticyInt>("TestInt");
		TestBool = CreateDefaultSubobject<UArticyBool>("TestBool");
		TestTest = CreateDefaultSubobject<UArticyBool>("TestTest");
		Var2 = CreateDefaultSubobject<UArticyBool>("Var2");
		C1_S1_Homarang_Fishing = CreateDefaultSubobject<UArticyBool>("C1_S1_Homarang_Fishing");
		Var5 = CreateDefaultSubobject<UArticyBool>("Var5");
	}
	
	void Init(UArticyGlobalVariables* const Store) 
	{
		/** initialize the variables */
		TestString->Init<UArticyString>(this, Store, TEXT("StringGlobals.TestString"), "Hello world");
		this->Variables.Add(TestString);
		TestInt->Init<UArticyInt>(this, Store, TEXT("StringGlobals.TestInt"), 2);
		this->Variables.Add(TestInt);
		TestBool->Init<UArticyBool>(this, Store, TEXT("StringGlobals.TestBool"), false);
		this->Variables.Add(TestBool);
		TestTest->Init<UArticyBool>(this, Store, TEXT("StringGlobals.TestTest"), false);
		this->Variables.Add(TestTest);
		Var2->Init<UArticyBool>(this, Store, TEXT("StringGlobals.Var2"), false);
		this->Variables.Add(Var2);
		C1_S1_Homarang_Fishing->Init<UArticyBool>(this, Store, TEXT("StringGlobals.C1_S1_Homarang_Fishing"), false);
		this->Variables.Add(C1_S1_Homarang_Fishing);
		Var5->Init<UArticyBool>(this, Store, TEXT("StringGlobals.Var5"), false);
		this->Variables.Add(Var5);
	}
};

UCLASS(BlueprintType)
class UPluginshowcaseNewVariableSetVariables : public UArticyBaseVariableSet
{
	GENERATED_BODY()
	
public:
	
	 UPluginshowcaseNewVariableSetVariables() 
	{
	}
	
	void Init(UArticyGlobalVariables* const Store) 
	{
		/** initialize the variables */
	}
};

/** Global Articy Variables */
UCLASS(BlueprintType)
class UPluginshowcaseGlobalVariables : public UArticyGlobalVariables
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Instanced, Category="StringGlobals")
	UPluginshowcaseStringGlobalsVariables* StringGlobals = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Instanced, Category="NewVariableSet")
	UPluginshowcaseNewVariableSetVariables* NewVariableSet = nullptr;
	
	 UPluginshowcaseGlobalVariables() 
	{
		/** create the namespaces */
		StringGlobals = CreateDefaultSubobject<UPluginshowcaseStringGlobalsVariables>("StringGlobals");
		NewVariableSet = CreateDefaultSubobject<UPluginshowcaseNewVariableSetVariables>("NewVariableSet");
		
		Init();
	}
	
	void Init() 
	{
		/** initialize the namespaces */
		StringGlobals->Init(this);
		this->VariableSets.Add(StringGlobals);
		NewVariableSet->Init(this);
		this->VariableSets.Add(NewVariableSet);
	}
	
	/** Get the default GlobalVariables (a copy of the asset). */
	UFUNCTION(BlueprintPure, Category="ArticyGlobalVariables", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyGV", keywords="global variables"))
	static UPluginshowcaseGlobalVariables* GetDefault(const UObject* WorldContext) 
	{
		return static_cast<UPluginshowcaseGlobalVariables*>(UArticyGlobalVariables::GetDefault(WorldContext));
	}
};
