// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "ArticyRuntime/Public/ArticyDatabase.h"
#include "PluginshowcaseExpressoScripts.h"
#include "PluginshowcaseDatabase.generated.h"

UCLASS(BlueprintType)
class UPluginshowcaseDatabase : public UArticyDatabase
{
	GENERATED_BODY()
	
public:
	 UPluginshowcaseDatabase() 
	{
		SetExpressoScriptsClass(UPluginshowcaseExpressoScripts::StaticClass());
	}
	
	/** Get the instace (copy of the asset) of the database. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyDB", keywords="database"))
	static UPluginshowcaseDatabase* Get(const UObject* WorldContext) 
	{
		return static_cast<UPluginshowcaseDatabase*>(Super::Get(WorldContext));
	}
	
	/** Get the global variables. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UPluginshowcaseGlobalVariables* GetGVs() const override
	{
		return static_cast<UPluginshowcaseGlobalVariables*>(Super::GetGVs());
	}
};
